# Generated by Django 5.0.4 on 2024-04-30 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\+996\\)\\d{9}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
